environment:
  APP_NAME: sample
  APP_ENV: test

# pipeline模板
pipeline: # <- steps
  - name: build
    environment:
      HELLO: hello-world
    tasks:
      - task.id: asl-tasks/sample
        arg1: hello-world-${env.HELLO}
      - package:
          fileset.includes: "jenkins.sh"
    when:
      environment:
        WORLD: hello

